version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: saas-postgres
    restart: always
    environment:
      POSTGRES_DB: studiobelle
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - saas-network

  redis:
    image: redis:7
    container_name: saas-redis-studiobelle
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - saas-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: saas-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - saas-network

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

networks:
  saas-network:
    driver: bridge